import { afterEach, beforeEach, describe, expect, it } from "vitest"
import fs from "node:fs"
import path from "node:path"
import os from "node:os"
import { analyzeLockfile, applyDedupeOverrides, generateOverridesDict } from "../src/scan/dedupe.js"

describe("Lockfile Deduplication & Transitive Bloat Analyzer", () => {
  let tmpDir: string

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "pkg-audit-dedupe-"))
  })

  afterEach(() => {
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true })
    } catch {
      // Ignore
    }
  })

  it("parses pnpm-lock.yaml and identifies duplicate transitive packages", () => {
    const mockPnpmLock = `
lockfileVersion: '6.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

packages:
  /@babel/core@7.24.0:
    resolution: {integrity: sha512-...}
    dependencies:
      semver: 7.6.0
    dev: false

  /@babel/core@7.18.5:
    resolution: {integrity: sha512-...}
    dependencies:
      semver: 6.3.0
    dev: true

  /lodash@4.17.21:
    resolution: {integrity: sha512-...}
    dev: false

  /lodash@4.17.15:
    resolution: {integrity: sha512-...}
    dev: false

  /lodash@4.17.11:
    resolution: {integrity: sha512-...}
    dev: true

  /zod@3.22.4:
    resolution: {integrity: sha512-...}
    dev: false
`
    fs.writeFileSync(path.join(tmpDir, "pnpm-lock.yaml"), mockPnpmLock, "utf8")

    const res = analyzeLockfile(tmpDir, "pnpm")
    expect(res).not.toBeNull()
    expect(res!.packageManager).toBe("pnpm")
    expect(res!.lockfileType).toBe("pnpm-lock.yaml")
    expect(res!.totalDuplicates).toBe(2) // @babel/core (2 versions), lodash (3 versions)

    const lodash = res!.duplicates.find((d) => d.name === "lodash")!
    expect(lodash).toBeDefined()
    expect(lodash.duplicateCount).toBe(3)
    expect(lodash.highestVersion).toBe("4.17.21")

    const babel = res!.duplicates.find((d) => d.name === "@babel/core")!
    expect(babel).toBeDefined()
    expect(babel.duplicateCount).toBe(2)
    expect(babel.highestVersion).toBe("7.24.0")
  })

  it("parses package-lock.json v3 and detects duplicate nested dependencies", () => {
    const mockNpmLock = {
      name: "monorepo",
      version: "1.0.0",
      lockfileVersion: 3,
      packages: {
        "": {
          name: "monorepo",
          dependencies: {
            "is-number": "^7.0.0",
          },
        },
        "node_modules/is-number": {
          version: "7.0.0",
        },
        "node_modules/old-tool/node_modules/is-number": {
          version: "3.0.0",
        },
        "node_modules/@scope/pkg": {
          version: "2.0.0",
        },
        "node_modules/nested/node_modules/@scope/pkg": {
          version: "1.5.0",
        },
      },
    }
    fs.writeFileSync(path.join(tmpDir, "package-lock.json"), JSON.stringify(mockNpmLock, null, 2), "utf8")

    const res = analyzeLockfile(tmpDir, "npm")
    expect(res).not.toBeNull()
    expect(res!.packageManager).toBe("npm")
    expect(res!.totalDuplicates).toBe(2)

    const isNum = res!.duplicates.find((d) => d.name === "is-number")!
    expect(isNum.highestVersion).toBe("7.0.0")

    const scopePkg = res!.duplicates.find((d) => d.name === "@scope/pkg")!
    expect(scopePkg.highestVersion).toBe("2.0.0")
  })

  it("parses yarn.lock and detects duplicate versions", () => {
    const mockYarnLock = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT MANUALLY.
# yarn lockfile v1

"chalk@^4.0.0":
  version "4.1.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-4.1.2.tgz#..."

"chalk@^2.4.2":
  version "2.4.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-2.4.2.tgz#..."

"tslib@^2.0.0":
  version "2.6.2"
  resolved "https://registry.yarnpkg.com/tslib/-/tslib-2.6.2.tgz#..."
`
    fs.writeFileSync(path.join(tmpDir, "yarn.lock"), mockYarnLock, "utf8")

    const res = analyzeLockfile(tmpDir, "yarn")
    expect(res).not.toBeNull()
    expect(res!.packageManager).toBe("yarn")
    expect(res!.totalDuplicates).toBe(1)

    const chalk = res!.duplicates[0]!
    expect(chalk.name).toBe("chalk")
    expect(chalk.duplicateCount).toBe(2)
    expect(chalk.highestVersion).toBe("4.1.2")
  })

  it("generates correct overrides dictionaries for highest and most-frequent strategies", () => {
    const duplicates = [
      {
        name: "lodash",
        versions: [
          { version: "4.17.21", dependents: ["a"] },
          { version: "4.17.15", dependents: ["b", "c", "d"] },
        ],
        suggestedVersion: "4.17.21",
        duplicateCount: 2,
        highestVersion: "4.17.21",
        mostFrequentVersion: "4.17.15",
      },
    ]

    const highest = generateOverridesDict(duplicates, "highest")
    expect(highest).toEqual({ lodash: "4.17.21" })

    const frequent = generateOverridesDict(duplicates, "most-frequent")
    expect(frequent).toEqual({ lodash: "4.17.15" })
  })

  it("applies pnpm.overrides, resolutions, and overrides to root package.json", () => {
    const pkgJson = {
      name: "my-monorepo",
      version: "1.0.0",
      private: true,
    }
    fs.writeFileSync(path.join(tmpDir, "package.json"), JSON.stringify(pkgJson, null, 2), "utf8")

    // 1. Apply pnpm overrides
    const pnpmRes = applyDedupeOverrides(tmpDir, { lodash: "4.17.21", "@babel/core": "7.24.0" }, "pnpm")
    expect(pnpmRes.ok).toBe(true)

    const pnpmContent = JSON.parse(fs.readFileSync(path.join(tmpDir, "package.json"), "utf8"))
    expect(pnpmContent.pnpm.overrides).toEqual({
      lodash: "4.17.21",
      "@babel/core": "7.24.0",
    })

    // 2. Apply yarn resolutions
    const yarnRes = applyDedupeOverrides(tmpDir, { chalk: "4.1.2" }, "yarn")
    expect(yarnRes.ok).toBe(true)

    const yarnContent = JSON.parse(fs.readFileSync(path.join(tmpDir, "package.json"), "utf8"))
    expect(yarnContent.resolutions).toEqual({ chalk: "4.1.2" })

    // 3. Apply npm overrides
    const npmRes = applyDedupeOverrides(tmpDir, { "is-number": "7.0.0" }, "npm")
    expect(npmRes.ok).toBe(true)

    const npmContent = JSON.parse(fs.readFileSync(path.join(tmpDir, "package.json"), "utf8"))
    expect(npmContent.overrides).toEqual({ "is-number": "7.0.0" })
  })
})
